### ISSUE TITLE
Grouping Classes in Manual Counts

### ISSUE THREAD

**Issue by hpreischel** [hsosik/ifcb-analysis#8]
Since the addition of class grouping when creating a training set in compile_train_features_user_training,  there is a need to create code that can group the same classes when performing manual counts. This will allow for class list consistency and for manual counts to be accurately compared to the grouped classifier in order to add adhoc thresholds to that classifier.

**Comment by hsosik** [comment]
Copying details from 8/18/16 email (Hannah to Heidi), in regards to running threshold_summary_TAMUG.m:

_>> threshold_summary_TAMUG
Error using histmulti5 (line 49)
Wrong number of bins in histmul5

Error in threshold_summary_TAMUG (line 35)
    [n,xbins,nbins]=histmulti5([x, y], [bins; bins]');

I think the underlying problem here is that class2use_manual and class2useTB do not match because the classes were grouped when creating the training set. This is causing imclass and many of the variables after it to be empty. Is there a way that we can group these classes together in the manual files as well so that both class2use variables will match?_

**Comment by hsosik** [comment]
Committed changes to countcells_allTB_class_by_thre_user.m and added threshold_summary_user.m (commit 140ffac9182eca43a0e5c89788cf054d781a6aec) to address this issue. Closing the issue for now, assuming Hannah finds the solution works for her.

**Comment by hsosik** [comment]
Apparently, I didn't actually add countcells_allTB_class_by_thre_user.m with the last commit, so tried again! Commit 9d02cf9
